FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY workers ./workers
COPY artifacts ./artifacts

CMD ["python", "workers/alert_worker.py"]