FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

# 🔥 OVERRIDE EVERYTHING
ENTRYPOINT ["bash", "-c"]

CMD ["bash", "-c", "echo '🚀 STARTING WORKER'; python workers/alert_worker.py 2>&1; echo '❌ WORKER CRASHED'; sleep 1000"]
