FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

# 🔥 OVERRIDE EVERYTHING
ENTRYPOINT ["bash", "-c"]

CMD ["echo '🚀 STARTING WORKER'; python workers/alert_worker.py; echo '❌ WORKER EXITED'; sleep 1000"]
