apiVersion: v1
kind: Secret
metadata:
  name: fraud-secrets
type: Opaque
stringData:
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  DATABASE_URL: postgresql://fraud:fraud@postgres:5432/frauddb
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: shamorrides@gmail.com
  SMTP_PASSWORD: rvnr gntu rrgr jyom
  SMTP_FROM: shamorrides@gmail.com
  SMTP_TO: sarfof06@gmail.com,romeokyere440@gmail.com

